define({
    BETA_TAB_LOCATOR: '//*[@href="/beta_tab/"]',
    RESULTS_COUNT_LOCATOR: '//strong[@data-reactid=".0.1.1.0.0.0"]',
    FILTER_BTN_ID: 'btn-filters',
    USERNAME_INPUT_ID: 'id_username',
    PASSWORD_INPUT_ID: 'id_password',
    LOGIN_BTN_LOCATOR: '#fm-form-login > * > button',
    PROFILE_LINK_LOCATOR: '#top-bar > *.my_profile > a',
    CHANNEL_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$channels.1"]',
    LANG_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$languages.1"]',
    ATTACHMENTS_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$hasMedia.1"]',
    CREATION_DATE_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.$dateRange.0.1.0:$placeholder"]',
    DISPLAY_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.$displayStatus.0.$checkboxRadioWrapper.$label.$input"]',
    MODERATION_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$cmsModerationStatus"]',
    TAGGING_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$cmsTaggingStatus"]',
    RM_FILTER_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$authorPermissionStatus"]',
    CLEAR_ALL_CHANNELS_LOCATOR:  '//*[@data-reactid=".0.1.0.0.1.0.0.1:$channels.1.3.0"]',
    FACEBOOK_CLEAR_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$channels.1.0:$FACEBOOK.0"]',
    GOOGLEPLUS_CLEAR_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$channels.1.0:$GOOGLEPLUS.0"]',
    GERMAN_CLEAR_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$languages.1.0:$de.0"]',
    FRENCH_CLEAR_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$languages.1.0:$fr.0"]',
    CLEAR_ALL_LANG_LOCATOR: '//*[@data-reactid=".0.1.0.0.1.0.0.1:$languages.1.3.0"]',
    MODAL_LOCATOR: '//div[@data-reactid=".1.1.0.0"]',
    MODAL_CLOSE_BTN_LOCATOR: '//button[@class="close"]',
    MODAL_NEXT_BTN1_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.0.1.0"]',
    MODAL_NEXT_BTN2_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.1.1.0"]',
    MODAL_NAV_RESET_BTN_LOCATOR: '//button[@data-reactid=".1.1.0.0.$=11.0.2.1.0"]',
    MODAL_TEXT1_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.0.0.1"]',
    MODAL_TEXT2_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.1.0.1"]',
    MODAL_TEXT3_LOCATOR: '//p[@data-reactid=".1.1.0.0.$=11.0.2.0.1"]'
});
